export const themes: Record<ThemeNames, Theme> = {
    Dark: {
        text: "#ddc",
        text_dim: "#abc",
        link: "#3cc",
        label: "#9ce",
        bg_main: "#123",
        bg_sub: "#234",
        border: "#345",
        honor_normal: "#998",
        honor_bronze: "#d83",
        honor_silver: "#adc",
        honor_gold: "#fb4",
        honor_platina: "#fe3",
        honor_rainbow: "#3f6",
        rank_b30: "#fc4",
        song_we: "#ed3",
        song_ult: "#3cf",
        song_mas: "#e9f",
        song_exp: "#e46",
        song_adv: "#e73",
        song_bas: "#1c3",
        clear_aj: "#fc1",
        clear_fc: "#5e7",
        bg_control: "#36b",
        text_control: "#eed"
    },
    Purple: {
        text: "#ddc",
        text_dim: "#aac",
        link: "#c3c",
        label: "#c9e",
        bg_main: "#103",
        bg_sub: "#224",
        border: "#436",
        honor_normal: "#998",
        honor_bronze: "#d83",
        honor_silver: "#adc",
        honor_gold: "#fb4",
        honor_platina: "#fe3",
        honor_rainbow: "#3f6",
        rank_b30: "#fc4",
        song_we: "#ed3",
        song_ult: "#3cf",
        song_mas: "#e9f",
        song_exp: "#e46",
        song_adv: "#e73",
        song_bas: "#1c3",
        clear_aj: "#fc1",
        clear_fc: "#5e7",
        bg_control: "#739",
        text_control: "#eed"
    }
}

export const themeNames = Object.keys(themes)