export const themes: Record<ThemeNames, Theme> = {
    Dark: {
        text: "#ddc",
        text_dim: "#abc",
        link: "#3cc",
        label: "#9ce",
        bg_main: "#123",
        bg_sub: "#234",
        border: "#345",
        honor_normal: "#998",
        honor_bronze: "#d83",
        honor_silver: "#adc",
        honor_gold: "#fb4",
        honor_rainbow: "#3f6",
        rank_b30: "#fc4",
        song_ult: "#3cf",
        song_mas: "#e9f",
        song_exp: "#e46",
        song_adv: "#e73",
        song_bas: "#1c3",
        clear_aj: "#5e7",
        clear_fc: "#fc1",
        switch_on: "#36b",
        switch_fill: "#eed"
    },
    Purple: {
        text: "#ddc",
        text_dim: "#aac",
        link: "#3cc",
        label: "#c9e",
        bg_main: "#103",
        bg_sub: "#224",
        border: "#436",
        honor_normal: "#998",
        honor_bronze: "#d83",
        honor_silver: "#adc",
        honor_gold: "#fb4",
        honor_rainbow: "#3f6",
        rank_b30: "#fc4",
        song_ult: "#3cf",
        song_mas: "#e9f",
        song_exp: "#e46",
        song_adv: "#e73",
        song_bas: "#1c3",
        clear_aj: "#5e7",
        clear_fc: "#fc1",
        switch_on: "#739",
        switch_fill: "#eed"
    },
    Light: {
        text: "#012",
        text_dim: "#999",
        link: "#3cc",
        label: "#576",
        bg_main: "#ffe",
        bg_sub: "#ddc",
        border: "#998",
        honor_normal: "#998",
        honor_bronze: "#c62",
        honor_silver: "#3cc",
        honor_gold: "#fb4",
        honor_rainbow: "#2b4",
        rank_b30: "#d2c",
        song_ult: "#3cf",
        song_mas: "#a0c",
        song_exp: "#c10",
        song_adv: "#f50",
        song_bas: "#373",
        clear_aj: "#1a3",
        clear_fc: "#c81",
        switch_on: "#3bd",
        switch_fill: "#ffe"
    },
}

export const themeNames = Object.keys(themes)