name: update-song-data
on: repository_dispatch
jobs:
  build-latest-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'data'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i
      - run: npm run main
        env:
          CHUNIREC_TOKEN: ${{ secrets.CHUNIREC_TOKEN }}
      - uses: test-room-7/action-update-file@v1
        with:
          branch: 'data'
          file-path: |
            data/jp.json
            log.md
          commit-msg: Update data/jp.json with GitHub actions
          github-token: ${{ secrets.GITHUB_TOKEN }}