name: update-song-data
on: repository_dispatch
jobs:
  build-latest-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm run buildData
      - uses: test-room-7/action-update-file@v1
        with:
            file-path: songData.json
            commit-msg: Update songData.json with GitHub actions
            github-token: ${{ secrets.GITHUB_TOKEN }}